### Test Order Creation
POST http://localhost:3000/orders
Content-Type: application/json

{
  "recipient": {
    "name": "Ollie the Second",
    "address1": "12 address avenue, Bankstown",
    "city": "Sydney",
    "state_code": "NSW",
    "country_code": "AU",
    "zip": "2200"
  },
  "items": [
    {
      "variant_id": 825,
      "quantity": 1,
      "files": [
        {
          "url": "http://idata.over-blog.com/1/10/29/90//femme-au-bar.jpg"
        }
      ]
    }
  ]
}
